name: CI

on:
  push:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Clone repo
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
         requirements.txt
        sparse-checkout-cone-mode: false

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
